Separate build and test jobs

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -11,8 +11,6 @@ on:
     branches:
       - master
 
-  workflow_dispatch:
-
 env:
   # Docker image
   # DOCKER_PASSWORD accessible via secrets
@@ -26,8 +24,8 @@ env:
 
 jobs:
 
-  test:
-    name: Build image and run tests
+  build:
+    name: Build image 
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -36,25 +34,13 @@ jobs:
         with:
           python-version: '3.7'
       - name: Install dependencies
-        run: |
-          python -m pip install -q --upgrade pip
-          python -m pip install -q cookiecutter git+https://github.com/TACC-Cloud/tapis-cli
-      - name: Authenticate Tapis client
-        run: |
-          touch ~/.tapis_firstrun
-          tapis auth init --no-git --no-registry --api-server $TAPIS_BASE_URL --username $TAPIS_USER --password ${{ secrets.TAPIS_PASSWORD }} -f json 
-          [ -d ~/.agave ] || (echo "could not find Tapis/Agave cache" &&  exit 1)
+        run: python -m pip install -q --upgrade pip cookiecutter
       - name: Get default actor context
         run: |
           python -m cookiecutter --no-input -fc main --directory sd2e_base https://github.com/TACC-Cloud/cc-tapis-v2-actors.git name=default_actor_context alias=default_actor_context
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
-      - name: Login to DockerHub
-        uses: docker/login-action@v1 
-        with:
-          username: ${{ env.DOCKER_USER }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      - name: Build and push
+      - name: Build Docker image
         uses: docker/build-push-action@v2
         with:
           context: .
@@ -64,7 +50,25 @@ jobs:
           cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}
           cache-to: type=inline
           tags: ${{ env.DOCKER_IMAGE }}
-      - name: Run tests
+
+  test:
+    name: Run image tests
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.7'
+      - name: Install Tapis CLI
+        run: python -m pip install -q --upgrade pip git+https://github.com/TACC-Cloud/tapis-cli
+      - name: Authenticate Tapis client
+        run: |
+          touch ~/.tapis_firstrun
+          tapis auth init --no-git --no-registry --api-server $TAPIS_BASE_URL --username $TAPIS_USER --password ${{ secrets.TAPIS_PASSWORD }} -f json 
+          [ -d ~/.agave ] || (echo "could not find Tapis/Agave cache" &&  exit 1)
+      - name: Test image using default CMD
         run: |
           docker run --rm -e _abaco_access_token=${TAPIS_TOKEN} \
             -e _abaco_api_server=${TAPIS_BASE_URL} \
