Use docker/build-push-action

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -27,7 +27,7 @@ env:
 jobs:
 
   test:
-    name: Build Docker image and run tests
+    name: Build image and run tests
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -39,13 +39,20 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           python -m pip install cookiecutter tapis-cli
-          jq --help || apt-get install -y jq
-      - name: Build image
-        run: DOCKER_IMAGE=${DOCKER_IMAGE} make -B image
+      - name: Build and push
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          pull: true
+          push: false
+          cache-from: type=registry,ref=enho/reactors:python3
+          cache-to: type=inline
+          # TODO: parametrize
+          tags: enho/reactors:python3 
       - name: Authenticate Tapis client
         run: |
-          TAPIS_TOKEN="$(tapis auth init --api-server $TAPIS_BASE_URL --username $TAPIS_USER --password {{ secrets.TAPIS_PASSWORD }} -f json | jq -rc .access_token)"
-          echo TAPIS_TOKEN=${TAPIS_TOKEN}
+          TAPIS_TOKEN="$(tapis auth init --api-server $TAPIS_BASE_URL --username $TAPIS_USER --password ${{ secrets.TAPIS_PASSWORD }} -f json | jq -rc .access_token)"
+          [ -z $TAPIS_TOKEN ] && echo "Error while retrieving Tapis token" && exit 1
           echo "::set-env name=TAPIS_TOKEN::$TAPIS_TOKEN"
       - name: Run tests
         run: |
@@ -63,7 +70,7 @@ jobs:
       - name: Check out the repo
         uses: actions/checkout@v2
       - name: Push to Docker Hub
-        uses: docker/build-push-action@v1
+        uses: docker/build-push-action@v2
         with:
           push: true
           username: $DOCKER_USER
